AntiAliasing 0
PreSharpen 0
Bloom 1
Technicolor 1
ToneMap 1
Sepia 1
PostSharpen 1
FxaaQualityPreset 6
FxaaQualitySubpix 5
FxaaQualityEdgeThreshold 7
FxaaQualityEdgeThresholdMin 5
HighQualitySharpen 0
AverageBlur 9
CoefficientsBlur 1
SharpenEdge 1
SharpenContour 1
BloomPreset 4
BloomThreshold 4
BloomWidth 4
BloomPower 4
TechniAmount 3
TechniPower 5
RedNegativeAmount 1
GreenNegativeAmount 1
BlueNegativeAmount 1
Gamma 5
Exposure 6
Saturation 8
Bleach 3
Defog 5
SepiaPower 1
GreyPower 2
Sharpen 5
BloomPresetToggle 1
Rawumber
